apiVersion: v1
kind: Service
metadata:
  name: chat-server
  namespace: app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: chat-server
  type: ClusterIP
status:
  loadBalancer: {}