apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-server
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-server
  template:
    metadata:
      labels:
        app: chat-server
    spec:
      volumes:
        - name: kafka-truststore
          configMap:
            name: kafka-truststore
      containers:
        - name: chat-server
          image: chat-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: kafka-truststore
            mountPath: /app/config
            readOnly: true
          envFrom:
            # ConfigMap에서 환경변수 가져오기
            - configMapRef:
                name: chat-server-config
            # Secret에서 환경변수 가져오기
            - secretRef:
                name: chat-server-secret



# mkdir -p /tmp/jar_extract && cd /tmp/jar_extract && jar -xf /app.jar