{{- range .Values.gateways }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ default "gateway" .name }}
  {{- with .namespace }}
  namespace: {{ .}}
  {{- end }}
  {{- with .labels }}
  labels:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ default "nginx" .spec.gatewayClassName }}
  {{- with .spec.infrastructure }}
  infrastructure:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  listeners:
    {{- range $listener := .spec.listeners }}
    - name: {{ $listener.name }}
      {{- with $listener.hostname }}
      hostname: {{ . | toYaml }}
      {{- end }}
      port: {{ $listener.port }}
      protocol: {{ $listener.protocol }}
      {{- with $listener.allowedRoutes }}
      allowedRoutes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $listener.tls }}
      tls:
        {{- toYaml . | nindent 8 }}
      {{- end}}
      {{- end }}
{{- end }}
