apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-frontend
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-frontend
  template:
    metadata:
      labels:
        app: chat-frontend
    spec:
      containers:
        - name: chat-frontend
          image: chat-frontend:newone
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: chat-frontend
  namespace: app
spec:
  type: NodePort # 미니쿠브 테스트용
  selector:
    app: chat-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31080
