apiVersion: v1
kind: ConfigMap
metadata:
  name: chatbot-config
  namespace: app
data:
  # Redis 설정
  REDIS_URL: "my-redis-master.redis.svc.cluster.local:6379"
  
  # JWT 설정
  ALGORITHM: "HS256"
  
  # AI 모델 설정
  EMBEDDING_MODEL_ID: "LTGrXJcB6Nm_Fkr-eYSL"
  LLM_MODEL_NAME: "gpt-3.5-turbo"
  
  # MySQL 설정
  MYSQL_HOST: "my-mysql.mysql.svc.cluster.local"
  MYSQL_PORT: "3306"
  MYSQL_USER: "thisismysqlusername"
  MYSQL_DB: "chat_db"
  
  # Frontend 설정
  FRONTEND_URL: "http://localhost:3001"
