apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: chatbot
  name: chatbot-server
  namespace: app
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: chatbot-server
status:
  loadBalancer: {}
